/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author katta
 */
public class CommunityReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityReportJPanel
     */
    public CommunityReportJPanel() {
        initComponents();
        Map<Integer, Integer> result = new HashMap<Integer, Integer>();
        Map<Patient, ArrayList<VitalSigns>> map = Patient.getEncounterHistory();
        for (Patient p : map.keySet()) {
            int communityId = p.getCommunity().getCommunityId();
            if (validateVitalSign(p)) {
                if (result.containsKey(communityId)) {
                    continue;
                }
                result.put(communityId, 0);
            } else {
                if (result.containsKey(communityId)) {
                    result.put(communityId, result.get(communityId) + 1);
                } else {
                    result.put(communityId, 1);
                }
            }
        }
        String[] columns = {"Community ID", "People with Abnormal Vitals"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        for (int i : result.keySet()) {
            Vector<String> row = new Vector<String>();
            row.add(String.valueOf(i));
            row.add(result.get(i).toString());
            model.addRow(row);
        }
        jTable1.setModel(model);

    }

    public static boolean validateVitalSign(Patient p) {

        Map<Patient, ArrayList<VitalSigns>> encoutersSign = Patient.getEncounterHistory();
        ArrayList<VitalSigns> result = encoutersSign.get(p);

        int n = result.size() - 1;

        if (n + 1 == 0) {
            System.out.println("No Patient records");
        }
        Double bloodPressure = result.get(n).getSysBP();
        int age = p.getAge();
        
                if(age==0){
            if(bloodPressure>=50 && bloodPressure<=70){
                return true;
            }
            else{
                return  false;
            }
        }
        else if(age<=1){
            if(bloodPressure>=70 && bloodPressure<=100){
                return true;
            }
            else{
                return  false;
            }
        }
        else if(age>=2 && age<=3){
            if(bloodPressure>=80 && bloodPressure<=110){
                return true;
            }
            else{
                return  false;
            }
        }
        else if(age>3 && age<=5){
            if(bloodPressure>=80 && bloodPressure<=110){
                return true;
            }
            else{
                return  false;
            }
        }
        else if(age>=6 && age<=12){
            if(bloodPressure>=80 && bloodPressure<=120){
                return true;
            }
            else{
                return  false;
            }
        }
        else{
            if(bloodPressure>=110 && bloodPressure<=120){
                return true;
            }
            else{
                return  false;
            }
        }
    }



/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Community Report");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Community ID", "People with Abnormal Vitals"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
