/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import carfleetmanager.carDetails;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author katta
 */
public class ListCarsManfPanelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListCarsManfPanel
     */
    public ListCarsManfPanelJPanel() {
        initComponents();
        ArrayList<String> manfList = new ArrayList<String>();
        String[] columns = {"Serial Num", "Manufacturer", "Model Num", "Year of Manf", "Min Seats", "Max Seats"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        try {
            Gson gson = new Gson();
            BufferedReader bufferedReader = new BufferedReader(new FileReader("C:\\Users\\katta\\OneDrive\\Documents\\NetBeansProjects\\Assignment2\\src\\config\\carData.json"));
            List<carDetails> cars = new Gson().fromJson(bufferedReader, new TypeToken<List<carDetails>>() {
            }.getType());
            for (carDetails detail : cars) {
                if (manfList.contains(detail.getManufacturer())) {
                    ;
                } else {
                    manfList.add(detail.getManufacturer());
                }
                Vector<String> row = new Vector<String>();
                row.add(detail.getSerialNumber());
                row.add(detail.getManufacturer());
                row.add(detail.getModelNumber());
                row.add(detail.getManfYear().toString());
                row.add(detail.getMinSeats().toString());
                row.add(detail.getMaxSeats().toString());
                model.addRow(row);
            }
            manfList.add(0, "");
            jComboBoxManf.setModel(new javax.swing.DefaultComboBoxModel<>(manfList.toArray(new String[0])));
            jTableListCars.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTableListCars = new javax.swing.JTable();
        lblManf = new javax.swing.JLabel();
        jComboBoxManf = new javax.swing.JComboBox<>();

        jTableListCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Serial Num", "Manufacturer", "Model Number", "Year of Manf", "Min Seats", "Max Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableListCars);

        lblManf.setText("Select Manufacturer");

        jComboBoxManf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxManf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxManfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jComboBoxManf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxManf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxManfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxManfActionPerformed
        // TODO add your handling code here:
        String selectedValue = jComboBoxManf.getSelectedItem().toString();
        String[] columns = {"Serial Num", "Manufacturer", "Model Num", "Year of Manf", "Min Seats", "Max Seats"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        try {
            Gson gson = new Gson();
            BufferedReader bufferedReader = new BufferedReader(new FileReader("C:\\Users\\katta\\OneDrive\\Documents\\NetBeansProjects\\Assignment2\\src\\config\\carData.json"));
            List<carDetails> cars = new Gson().fromJson(bufferedReader, new TypeToken<List<carDetails>>() {
            }.getType());
            for (carDetails detail : cars) {
                Vector<String> row = new Vector<String>();
                String manufacturer = detail.getManufacturer();
                if (manufacturer.equalsIgnoreCase(selectedValue)) {
                    row.add(detail.getSerialNumber());
                    row.add(detail.getManufacturer());
                    row.add(detail.getModelNumber());
                    row.add(detail.getManfYear().toString());
                    row.add(detail.getMinSeats().toString());
                    row.add(detail.getMaxSeats().toString());
                    model.addRow(row);
                } else if (selectedValue.isBlank()) {
                    row.add(detail.getSerialNumber());
                    row.add(detail.getManufacturer());
                    row.add(detail.getModelNumber());
                    row.add(detail.getManfYear().toString());
                    row.add(detail.getMinSeats().toString());
                    row.add(detail.getMaxSeats().toString());
                    model.addRow(row);
                } else {;
                }

            }
            //            cityList.add(0, "");
            //            jComboBoxCity.setModel(new javax.swing.DefaultComboBoxModel<>(cityList.toArray(new String[0])));
            jTableListCars.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxManfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxManf;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableListCars;
    private javax.swing.JLabel lblManf;
    // End of variables declaration//GEN-END:variables
}
