/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;

/**
 *
 * @author katta
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        File file = new File("C:\\Users\\katta\\OneDrive\\Documents\\NetBeansProjects\\Assignment2\\src\\config\\carData.json");
        txtLastCatalogUpdate.setText(sdf.format(file.lastModified()).toString());
        txtLastCatalogUpdate.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        ctrlPanel = new javax.swing.JPanel();
        btnListCars = new javax.swing.JButton();
        btnListCarsManf = new javax.swing.JButton();
        btnListCarsManfYear = new javax.swing.JButton();
        btnListCarSerialNum = new javax.swing.JButton();
        btnListCarModelNum = new javax.swing.JButton();
        btnListManf = new javax.swing.JButton();
        btnListCarSeats = new javax.swing.JButton();
        btnCarAvailability = new javax.swing.JButton();
        btnCreateCar = new javax.swing.JButton();
        btnListExpiredMC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLastCatalogUpdate = new javax.swing.JTextField();
        lblLastCatalogUpdate = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        btnListCars.setText("List All Cars");
        btnListCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsActionPerformed(evt);
            }
        });

        btnListCarsManf.setText("Based on Manufacturer");
        btnListCarsManf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsManfActionPerformed(evt);
            }
        });

        btnListCarsManfYear.setText("Based on Manufactured Year");
        btnListCarsManfYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsManfYearActionPerformed(evt);
            }
        });

        btnListCarSerialNum.setText("Based on Serial Number");
        btnListCarSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarSerialNumActionPerformed(evt);
            }
        });

        btnListCarModelNum.setText("Based on Model Number");
        btnListCarModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarModelNumActionPerformed(evt);
            }
        });

        btnListManf.setText("List Manufacturers");
        btnListManf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListManfActionPerformed(evt);
            }
        });

        btnListCarSeats.setText("Based on Number of Seats");
        btnListCarSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarSeatsActionPerformed(evt);
            }
        });

        btnCarAvailability.setText("Car Availability");
        btnCarAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarAvailabilityActionPerformed(evt);
            }
        });

        btnCreateCar.setText("Add Car Details");
        btnCreateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCarActionPerformed(evt);
            }
        });

        btnListExpiredMC.setText("List Cars with Expired Maintenace ");
        btnListExpiredMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListExpiredMCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FIND CARS");

        txtLastCatalogUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblLastCatalogUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLastCatalogUpdate.setText("LAST CATALOG UPDATE:");

        javax.swing.GroupLayout ctrlPanelLayout = new javax.swing.GroupLayout(ctrlPanel);
        ctrlPanel.setLayout(ctrlPanelLayout);
        ctrlPanelLayout.setHorizontalGroup(
            ctrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctrlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ctrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnListCarSerialNum)
                    .addComponent(btnListCarsManfYear)
                    .addComponent(btnListCarsManf)
                    .addComponent(btnListCars)
                    .addComponent(btnListCarModelNum)
                    .addComponent(btnListManf)
                    .addComponent(btnListCarSeats)
                    .addComponent(btnCarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateCar)
                    .addComponent(btnListExpiredMC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ctrlPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctrlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ctrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLastCatalogUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(lblLastCatalogUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ctrlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCarAvailability, btnCreateCar, btnListCarModelNum, btnListCarSeats, btnListCarSerialNum, btnListCars, btnListCarsManf, btnListCarsManfYear, btnListExpiredMC, btnListManf, txtLastCatalogUpdate});

        ctrlPanelLayout.setVerticalGroup(
            ctrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctrlPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLastCatalogUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLastCatalogUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnCarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateCar)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListCars)
                .addGap(18, 18, 18)
                .addComponent(btnListCarsManf)
                .addGap(18, 18, 18)
                .addComponent(btnListCarsManfYear)
                .addGap(18, 18, 18)
                .addComponent(btnListCarSerialNum)
                .addGap(18, 18, 18)
                .addComponent(btnListCarModelNum)
                .addGap(18, 18, 18)
                .addComponent(btnListCarSeats)
                .addGap(18, 18, 18)
                .addComponent(btnListExpiredMC)
                .addGap(73, 73, 73)
                .addComponent(btnListManf)
                .addGap(22, 22, 22))
        );

        splitPane.setLeftComponent(ctrlPanel);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CAR FLEET MANAGER");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(displayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsActionPerformed
        // TODO add your handling code here:
        ListAllCarsJPanel listAllCars = new ListAllCarsJPanel();
        splitPane.setRightComponent(listAllCars);

    }//GEN-LAST:event_btnListCarsActionPerformed

    private void btnListCarsManfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsManfActionPerformed

        ListCarsManfPanelJPanel listAllCarsManf = new ListCarsManfPanelJPanel();
        splitPane.setRightComponent(listAllCarsManf);
    }//GEN-LAST:event_btnListCarsManfActionPerformed

    private void btnListCarsManfYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsManfYearActionPerformed
        // TODO add your handling code here:
        ListCarsManfYearJPanel listCarsManfYear = new ListCarsManfYearJPanel();
        splitPane.setRightComponent(listCarsManfYear);
    }//GEN-LAST:event_btnListCarsManfYearActionPerformed

    private void btnListCarSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarSerialNumActionPerformed
        // TODO add your handling code here:
        ListCarSerialNumberJPanel listCarsSerialNum = new ListCarSerialNumberJPanel();
        splitPane.setRightComponent(listCarsSerialNum);
    }//GEN-LAST:event_btnListCarSerialNumActionPerformed

    private void btnListCarModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarModelNumActionPerformed
        // TODO add your handling code here:
        ListCarsModelNumberJPanel listCarsModelNum = new ListCarsModelNumberJPanel();
        splitPane.setRightComponent(listCarsModelNum);
    }//GEN-LAST:event_btnListCarModelNumActionPerformed

    private void btnListManfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListManfActionPerformed
        // TODO add your handling code here:
        ListManufacturersJPanel listManf = new ListManufacturersJPanel();
        splitPane.setRightComponent(listManf);
    }//GEN-LAST:event_btnListManfActionPerformed

    private void btnListCarSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarSeatsActionPerformed
        // TODO add your handling code here:
        ListCarSeatsJPanel listCarSeats = new ListCarSeatsJPanel();
        splitPane.setRightComponent(listCarSeats);
    }//GEN-LAST:event_btnListCarSeatsActionPerformed

    private void btnCarAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarAvailabilityActionPerformed
        // TODO add your handling code here:
        ListAvailableCarsJPanel listAvlblCars = new ListAvailableCarsJPanel();
        splitPane.setRightComponent(listAvlblCars);
    }//GEN-LAST:event_btnCarAvailabilityActionPerformed

    private void btnCreateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCarActionPerformed
        // TODO add your handling code here:
        CreateCarJPanel createCar = new CreateCarJPanel();
        splitPane.setRightComponent(createCar);
    }//GEN-LAST:event_btnCreateCarActionPerformed

    private void btnListExpiredMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListExpiredMCActionPerformed
        // TODO add your handling code here:
        ListCarsExpiredMCJPanel listCarsExpiredMC = new ListCarsExpiredMCJPanel();
        splitPane.setRightComponent(listCarsExpiredMC);
    }//GEN-LAST:event_btnListExpiredMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarAvailability;
    private javax.swing.JButton btnCreateCar;
    private javax.swing.JButton btnListCarModelNum;
    private javax.swing.JButton btnListCarSeats;
    private javax.swing.JButton btnListCarSerialNum;
    private javax.swing.JButton btnListCars;
    private javax.swing.JButton btnListCarsManf;
    private javax.swing.JButton btnListCarsManfYear;
    private javax.swing.JButton btnListExpiredMC;
    private javax.swing.JButton btnListManf;
    private javax.swing.JPanel ctrlPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLastCatalogUpdate;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtLastCatalogUpdate;
    // End of variables declaration//GEN-END:variables
}
